INSERT INTO DATES(DATE_) VALUES(GETDATE())

SELECT * FROM DATES

declare @I AS INT=0
WHILE @I<5
BEGIN
    INSERT INTO DATES (DATE_)
	VALUES (GETDATE())
	WAITFOR DELAY '00:00:02'--SQL BEKLETME KOMUTU
	SET @I=@I+1
END

SELECT * INTO DATES1 FROM DATES--DATES TOPLOSUNDA KAYITLARI KOPYALA DATES1 ADINDA TABLO OLUSTURARAK ICINE YAPISTIR

SP_SPACEUSED 'DATES'--TABLO BOYUTUNU VERIR