-----------------------------------------CURSOR-------------------------
/*
  BIR DATA SET  ICERSINDE GELEN VERILERI DONGU ICERSINDE KULLNMAK ICIN CURSOR KAVRAMINI KULLANIRIZ.
*/

DECLARE @NAMESURNAME AS VARCHAR(50)=''
DECLARE @AGE AS INT
DECLARE @EMAIL AS VARCHAR(100)=''
DECLARE @MSG AS VARCHAR(500)=''

DECLARE CRS CURSOR FOR
        SELECT NAMESURNAME,DATEDIFF(YEAR,BIRTHDATE,GETDATE()) AS AGE,EMAIL
		     FROM USERS
	    WHERE DAY(BIRTHDATE)=25 AND, MONTH(BIRTHDATE)=4
OPEN CRS 
FETCH NEXT FROM CRS INTO @NAMESURNAME, @AGE,@EMAIL

WHILE @@FETCH_STATUS=0
BEGIN
SET @MSG = 'SAYIN'+@NAMESURNAME+', DOGUM GUNUNUZ KUTLU OLSUN. '+CONVERT(VARCHAR,@AGE)+'. YASINIZ KUTLAR, NICE MUTLU YILLARA DILERIZ.'

EXEC MSDB.DBO.sp_send_dbmail @profile_name='SQLMAIL'
@SUBJECT='MUTLU YILLAR'
@BODY=@MSG,
@recipients=@EMAIL

FETCH NEXT FROM CRS INTO @NAMESURNAME,@AGE,@EMAIL
END
CLOSE CRS
DEALLOCATE CRS