-----------DONGULER-----------

DECLARE @I AS INT=0
WHILE @I<10
BEGIN
/*SELECT@I*/ PRINT @I
SET @I=@I+1
END


DECLARE @I AS INT=0
WHILE @I<10
BEGIN
INSERT INTO TARIHLER(TARIH) VALUES(GETDATE())
WAITFOR DELAY '00:00:01' --1SANIYE BEKLE
SET @I=@I+1
END
TRUNCATE TABLE TARIHLER
SELECT * FROM TARIHLER

--RAND() RASTGELE SAYI URETIR
DECLARE @I AS INT=0
DECLARE @TARIH AS DATE 
WHILE @I<1
BEGIN
SET @TARIH=DATEADD(DAY,ROUND(RAND()*18250,0),'1950-05-13')

SET @I=@I+1
END
SELECT @TARIH

--SP_SPACEUSED 'TARIHLER' //TABLO'NUN BOYUTUNA BAKMAYI SAGLAYAN KOMUT 

/*
    CREATE NONCLUSTERED INDEX IX1 ON TARIHLER
	(
	  TARIH
	)

	SELECT *FROM TARIHLER
	WHERE TARIH = '2005-05-08'

-- INDEXES HIZLI VERI OKUMAYI SAGLAR----
*/

/*
        INDEX BOZULMALARINI DUZELTME 
REBULD = SIL BASTAN SIRALAMA YAPAR
FRAGMENTATION %40UZERINDEYSE KULLANILABILIR 
GARANTI OLSUN DIE HERZAMANDA YAPILABILIR

REORGANIZE = KENDI ICERSINDE SIRALAMA GERCEKLESTIRIR 
FRAGMENTATION %40ALTINDAYSA KULLANILABILIR

FILL FACTOR DEGERINDE %30 VEYA %40 ORANINDA BOS ALAN BIRAKILIRSA BU BOZULMA SIKLIGI UZATILABILIR
*/

----ISTATISTIKLER----
/*
 SP_UPDATESTATS --TUM TABLOLARIN ISTATISTIKLERINI GUNCELLER

 UPDATE STATISTICS CUSTOMER --SADECE CUSTOMER TABLOSUNUN ISTATISTIKLERINI GUNCELLER
*/