USE ETRADE

SELECT * FROM CUSTOMERS 

ORDER BY CITY DESC

WHERE BIRTHDATE>'19750101'

INSERT INTO CUSTOMERS(CUSTOMERNAME,CITY,BIRTHDATE,DISTRICT,GENDER) VALUES('Leyla Aný','Ýzmir','2003-12-05','Karþýyaka','K')

UPDATE CUSTOMERS SET NATION='TR',AGE=DATEDIFF(YEAR,BIRTHDATE,GETDATE()) --DATEDIFF FONKSÝYONU 2 TARÝH ARASINDAKÝ FARKI ALIR

DELETE FROM CUSTOMERS--TABLOYU TAMAMEN BOÞALTIR PRÝMARY KEY ALANINI KALDIÐI YERDEN DEVAM ETTÝRÝR

TRUNCATE TABLE CUSTOMERS --TABLOYU TAMAMEN BOÞALTIR PRÝMARY KEY ALANINIDA SIFIRLAR

UPDATE CUSTOMERS SET GENDER='Erkek' WHERE GENDER='E'

SELECT DISTINCT GENDER FROM CUSTOMERS

SELECT TOP 3 /*PERCENT*/ * FROM CUSTOMERS WHERE GENDER='Erkek' ORDER BY CUSTOMERNAME ASC/*TOP 3 PERCENT ="YÜZDE 3'NÜ GETÝRÝR "*/
