
--TABLOLAR--

--COUNTRY TABLOSU
CREATE TABLE COUNTRIES(
ID TINYINT IDENTITY(1,1),
COUNTRY VARCHAR(50)
CONSTRAINT PK_COUNTRIES PRIMARY KEY CLUSTERED(ID ASC))

--USER TABLOSU
CREATE TABLE USERS(
ID INT IDENTITY(1,1),
USERNAME_ VARCHAR(50),
PASSWORD_ VARCHAR(50),
NAMESURNAME VARCHAR(100),
EMAIL VARCHAR(100),
GENDER VARCHAR(1),
BIRTHDATE DATE,
CREATEDDATE DATETIME,
TELNR1 VARCHAR(15),
TELNR2 VARCHAR(15)
CONSTRAINT PK_USERS PRIMARY KEY CLUSTERED (ID ASC))

--ITEM TABLOSU
CREATE TABLE ITEMS(
ID INT IDENTITY(1,1),
ITEMCODE VARCHAR(50),
ITEMNAME VARCHAR(100),
UNITPRICE FLOAT,
CATEGORY1 VARCHAR(50),
CATEGORY2 VARCHAR(50),
CATEGORY3 VARCHAR(50),
CATEGORY4 VARCHAR(50),
BRAND VARCHAR(50)
CONSTRAINT PK_ITEMS PRIMARY KEY CLUSTERED (ID ASC))

--PAYMENT TABLOSU
CREATE TABLE PAYMENTS(
ID INT IDENTITY(1,1),
ORDERID INT,
PAYMENTTYPE TINYINT,
DATE_ DATETIME,
ISOK BIT,
APPROVECODE VARCHAR(100),
PAYMENTTOTAL FLOAT
CONSTRAINT PK_PAYMENTS PRIMARY KEY CLUSTERED (ID ASC))

--ADDRESS TABLOSU
CREATE TABLE ADDRESS(
ID INT IDENTITY(1,1),
USERID INT,
COUNTRYID TINYINT,
CITYID SMALLINT,
TOWNID INT,
DISTRICTID INT,
POSTALCODE VARCHAR(10),
ADDRESSTEXT VARCHAR(500)
CONSTRAINT PK_ADDRESS PRIMARY KEY CLUSTERED (ID ASC))

--ORDER TABLOSU
CREATE TABLE ORDERS(
ID INT IDENTITY(1,1),
USERID INT,
DATE_ DATETIME,
TOTALPRICE FLOAT,
STATUS_ TINYINT,
ADDRESSID INT
CONSTRAINT PK_ORDERS PRIMARY KEY CLUSTERED (ID ASC))

--ORDERDETAIL TABLOSU
CREATE TABLE ORDERDETAILS(
ID INT IDENTITY(1,1),
ORDERID INT,
ITEMID INT,
AMOUNT INT,
UNITPRICE FLOAT,
LINETOTAL FLOAT
CONSTRAINT PK_ORDERDETAILS PRIMARY KEY CLUSTERED (ID ASC))

--CITY TABLOSU
CREATE TABLE CITIES(
ID SMALLINT IDENTITY(1,1),
COUNTRYID TINYINT,
CITY VARCHAR(50)
CONSTRAINT PK_CITIES PRIMARY KEY CLUSTERED (ID ASC))

--TOWN TABLOSU
CREATE TABLE TOWNS(
ID INT IDENTITY(1,1),
CITYID SMALLINT,
TOWN VARCHAR(50)
CONSTRAINT PK_TOWNS PRIMARY KEY CLUSTERED (ID ASC))

--DISTRICT TABLOSU
CREATE TABLE DISTRICTS(
ID INT IDENTITY(1,1),
TOWNID INT,
DISTRICT VARCHAR(50)
CONSTRAINT PK_DISTRICTS PRIMARY KEY CLUSTERED (ID ASC))

--INVOICES TABLOSU
CREATE TABLE INVOICES(
ID INT IDENTITY(1,1),
ORDERID INT,
DATE_ DATETIME,
ADDRESSID INT,
CARGOFICHENO VARCHAR(20),
TOTALPRICE FLOAT
CONSTRAINT PK_INVOICES PRIMARY KEY CLUSTERED (ID ASC))

--INVOICE DETAIL TABLOSU
CREATE TABLE INVOICEDETAILS(
ID INT IDENTITY(1,1),
INVOICEID INT,
ORDERDETAILID INT,
ITEMID INT,
AMOUNT INT,
UNITPRICE FLOAT,
LINETOTAL FLOAT
CONSTRAINT PK_INVOICEDETAILS PRIMARY KEY CLUSTERED (ID ASC))



--COUNTRY TABLOSU VERI GIRME--
SELECT * FROM COUNTRIES

INSERT INTO COUNTRIES(COUNTRY) VALUES('TÜRKÝYE'),
INSERT INTO COUNTRIES(COUNTRY) VALUES('ALMANYA'),
INSERT INTO COUNTRIES(COUNTRY) VALUES('ÝNGÝLTERE'),
INSERT INTO COUNTRIES(COUNTRY) VALUES('RUSYA'),
INSERT INTO COUNTRIES(COUNTRY) VALUES('NORVEÇ')

--CITIY TABLOSU VERI GIRME--
SELECT *FROM CITIES
INSERT INTO CITIES(COUNTRYID,CITY) VALUES('1','ANKARA'),
INSERT INTO CITIES(COUNTRYID,CITY) VALUES('2','BERLÝN'),
INSERT INTO CITIES(COUNTRYID,CITY) VALUES('3','LONDRA'),
INSERT INTO CITIES(COUNTRYID,CITY) VALUES('4','MOSKOVA'),
INSERT INTO CITIES(COUNTRYID,CITY) VALUES('5','BERGEN')

--TOWN TABLOSU VERI GIRME--
SELECT * FROM TOWNS
INSERT INTO TOWNS(CITYID,TOWN) VALUES('1','BEYPAZARI'),
INSERT INTO TOWNS(CITYID,TOWN) VALUES('2','PANKOW'),
INSERT INTO TOWNS(CITYID,TOWN) VALUES('3','WESTMINSTER')

--DISTRICT TABLOSU VERI GIRME--
SELECT * FROM DISTRICTS
INSERT INTO DISTRICTS(TOWNID,DISTRICT) VALUES('1','ACISU MAH.')
TRUNCATE TABLE DISTRICTS

--USER TABLOSU VERI GIRME--
SELECT * FROM USERS
INSERT INTO USERS(USERNAME_,PASSWORD_,NAMESURNAME,EMAIL,GENDER,BIRTHDATE,CREATEDDATE,TELNR1,TELNR2) VALUES('user1','1234','HASAN ATIK','user@gmail.com','E','2002-05-25','2023-12-01 14:25','5879637852','5748514578')
TRUNCATE TABLE USERS

--ADDRESS TABLOSU VERI GIRME--
SELECT * FROM ADDRESS
INSERT INTO ADDRESS(USERID,COUNTRYID,CITYID,TOWNID,DISTRICTID,POSTALCODE,ADDRESSTEXT) VALUES('1','1','1','1','1','16000','CEYHAN SOKAK YOKSUL APT. KAT 2 DAIRE NO:07')

--TABLODAN ID ILE VERI CEKME--
SELECT * FROM USERS WHERE ID=1
SELECT * FROM ADDRESS WHERE USERID=1

--ILISKISEL VERI CEKME--
SELECT USERS.*,ADDRESS.ADDRESSTEXT FROM
USERS,ADDRESS
WHERE USERS.ID=ADDRESS.USERID
AND USERS.ID=1

--ALIAS KULLANIMI--
SELECT
U.NAMESURNAME AS ADSOYAD,
U.EMAIL MAILADRESI,
U.GENDER CINSIYET,
U.BIRTHDATE DOGUMTARIHI,
C.COUNTRY AS ULKE,CT.CITY SEHIR,T.TOWN ILCE,D.DISTRICT SEMT,
A.POSTALCODE POSTAKODU,A.ADDRESSTEXT AS ACIKADRES
FROM
USERS U,ADDRESS A,COUNTRIES C,CITIES CT,TOWNS T, DISTRICTS D
WHERE U.ID=A.USERID AND C.ID=A.COUNTRYID AND CT.ID=A.CITYID
AND T.ID=A.TOWNID AND D.ID=A.DISTRICTID 
--AND U.ID=1
AND CT.CITY LIKE 'ANKARA'
ORDER BY U.NAMESURNAME

--JOIN ORNEK--
SELECT U.NAMESURNAME,U.EMAIL,A.ADDRESSTEXT,
C.COUNTRY,CT.CITY,T.TOWN,D.DISTRICT FROM
USERS U 
JOIN ADDRESS A ON A.USERID=U.ID
JOIN COUNTRIES C ON C.ID=A.COUNTRYID
JOIN CITIES CT ON CT.ID=A.CITYID
JOIN TOWNS T ON T.ID=A.TOWNID
JOIN DISTRICTS D ON D.ID=A.DISTRICTID

SELECT CT.CITY,COUNT(U.ID) AS KULLANICISAYISI FROM
USERS U 
JOIN ADDRESS A ON A.USERID=U.ID
JOIN COUNTRIES C ON C.ID=A.COUNTRYID
JOIN CITIES CT ON CT.ID=A.CITYID
JOIN TOWNS T ON T.ID=A.TOWNID
JOIN DISTRICTS D ON D.ID=A.DISTRICTID
GROUP BY CT.CITY