INSERT INTO WORKERS
(WORKERCODE, WORKERNAME, GENDER, BIRTHDATE, TCNO, WORKERBARCODE)
VALUES('123456789','HASAN ATIK','E','20020525','123456789',NEWID())--NEWID() RASTGELE ID URETIR.

SELECT * FROM WORKERS
SELECT * FROM WORKERTRANSACTIONS
TRUNCATE TABLE WORKERTRANSACTIONS

INSERT INTO WORKERTRANSACTIONS
(WORKERID, DATE_, IOTYPE, GATEID)
VALUES(1,'2023-05-01 08:30:00','G',3)

------------------------STORED PROCEDURE----------------------
SELECT * FROM WORKERS WHERE WORKERBARCODE='2D9CAE63-F80A-4B41-AB2C-62BFDB267765'

ALTER PROCEDURE SP_CARD_CONTROL--ALTER,CREATE,DROP
@WORKERBARCODE AS VARCHAR(50)--PROSEDUR ICIN PARAMETRE OLUSTURURDU.
AS
BEGIN
    IF EXISTS(SELECT * FROM WORKERS WHERE WORKERBARCODE=@WORKERBARCODE)
	BEGIN
	   SELECT 'KART DOGRU' 
	END
    ELSE
	BEGIN
	   SELECT 'KART HATALI'
	END

END

ALTER PROCEDURE SP_CARD_CONTROL--ALTER,CREATE,DROP
@WORKERBARCODE AS VARCHAR(50)--PROSEDUR ICIN PARAMETRE OLUSTURURDU.
AS
BEGIN
   DECLARE @WORKERNAME AS VARCHAR(100)
   SELECT @WORKERNAME=WORKERNAME FROM WORKERS WHERE WORKERBARCODE=@WORKERBARCODE
   IF @WORKERNAME IS NULL
	BEGIN
	   RAISERROR('KART GECERSIZ',16,1)--T-SQL KULLANICIYA HATA BASMA KOMUTUDUR 16,1SABITTIR /* SELECT 'KART HATALI' */ 
	   RETURN --ALT SATIRLARA DEVAM ETMEZ.
	END
    ELSE
	BEGIN
	   SELECT @WORKERNAME
	END

END

CREATE PROC SP_WORKER_INOUT
@WORKERBARCODE AS VARCHAR(50),
@DATE AS DATETIME,
@IOTYPE AS VARCHAR(1),
@GATEID AS INT
AS
BEGIN
DECLARE @WORKERNAME AS VARCHAR(100)
DECLARE @WORKERID AS INT
SELECT @WORKERNAME=WORKERNAME,@WORKERID=ID FROM WORKERS 
WHERE WORKERBARCODE=@WORKERBARCODE
    IF @WORKERID IS NULL
	BEGIN
	   RAISERROR ('OKUTULAN KART GECERSIZDIR',16,1)
	   RETURN
    END


DECLARE @LASTIO AS VARCHAR(1)

SELECT TOP 1 @LASTIO=IOTYPE FROM WORKERTRANSACTIONS
WHERE WORKERID=1 AND DATE_>=CONVERT(DATE,GETDATE())
ORDER BY DATE_ DESC

     IF @LASTIO=@IOTYPE
	 BEGIN
	    IF @IOTYPE='G'
		BEGIN
		   RAISERROR('ZATEN ICERIDE GORUNUYORSUNUZ, GIRIS YAPAMAZSINIZ',16,1)
		   RETURN
		END
		 IF @IOTYPE='C'
		BEGIN
		   RAISERROR('ZATEN DISARIDA GORUNUYORSUNUZ, CIKIS YAPAMAZSINIZ',16,1)
		   RETURN
		END
	  END

INSERT INTO WORKERTRANSACTIONS(WORKERID,DATE_,IOTYPE,GATEID)
VALUES(@WORKERID,@DATE,@IOTYPE,@GATEID)

SELECT @WORKERNAME AS WORKERNAME,@DATE AS DATE_,@IOTYPE AS IOTYPE
END


------------------STORED PROCEDURE CAGIRMA------------
EXEC SP_CARD_CONTROL @WORKERBARCODE='2D9CAE63-F80A-4B41-AB2C-62BFDB267765'--PARAMETRELERIN SIRA ONEMI YOKTUR.
/*
EXEC SP_CARD_CONTROL '2D9CAE63-F80A-4B41-AB2C-62BFDB267765' PARAMETRELER SIRAYLA YAZILMALIDIR.
*/
EXEC SP_WORKER_INOUT '2D9CAE63-F80A-4B41-AB2C-62BFDB267765','2023-05-12 08:10:00','G',1


-------------------------------------ornek---------------------------------------
CREATE TABLE #RAPOR --GECICI TEMP TABLO
(KULLANICIADI) VARCHAR(100),ADSOYAD VARCHAR(100))
INSERT INTO #RAPOR
EXEC SP_SATISLAR '20190101','20191231','%'

SELECT KATEGORI1,SUM(SATIRTOPLAMI) FROM #RAPOR

DROP TABLE #RAPOR--SPROCEDURE TEMP TABLEYE KAYIT ATMA