/*
TRANSACTION VERI TABANI TEK BLOK KODLARDA OTOMATIK KENDI YAPAR AMA BIRDEN FAZLA KI
KOD BLOKLU ISLEMLERDE KENDIMIZ KONTROL ETMEMIZ GEREKIR.
*/

---------------ORNEK--------------------------
SELECT * FROM ITEMS WHERE ID=3
BEGIN TRAN
UPDATE ITEMS SET UNITPRICE=55 WHERE ID=3
--BURAYA KADAR TRANSACTION ACIK 
ROLLBACK--TABLODAKI KAYITTA DEGISIKLIK OLMAZ

SELECT *FROM ITEMS
WITH (NOLOCK)--ACIK TRANSACTION KAYDINI BITIRILMIS SEKILDE GETIRIR
DBCC OPENTRAN--ACIK TRANSACTIONLARI GOSTERIR