USE ETRADE
SELECT
U.USERNAME_ KULLANICIADI,ITM.ITEMNAME URUNADI
CREATE VIEW VWORDERS --CREATE , ALTER , DROP ILE OLUSTURULUP SILINIR DEGISTIRILIR 
AS
FROM
ORDERDETAILS OD
INNER JOIN USERS U ON U.ID=O.USERID
INNER JOIN ITEMS ITM ON ITM.ID=OD.ITEMID
WHERE U.USERNAME_ = 'Z_DALAMANLI'

SELECT * FROM VWORDERS
WHERE KULLANICIADI='Z_DALAMANLI' 

SELECT------------------------------SQL SORGUSUNUN BIR TABLO GIBI KULLANILDIGI YAPILARA VIEW DENIR
SEHIR, SUM(SATIRTOPLAMI),COUNT(*)
FROM VWORDERS
GROUP BY SEHIR